mod minor  conditions.yml

diff --git a/.github/workflows/conditions.yml b/.github/workflows/conditions.yml
--- a/.github/workflows/conditions.yml
+++ b/.github/workflows/conditions.yml
@@ -17,6 +17,7 @@ jobs:
         run: echo "This runs only on main branch"
 
       - name: Step that fails intentionally
+        continue-on-error: true
         run: exit 1
 
       - name: Run only if previous step failed
@@ -25,10 +26,9 @@ jobs:
 
       - name: Continue even if error occurs
         continue-on-error: true
-        run: exit 1
-      #  run: |
-       #   echo "This step will fail but workflow continues"
-       #   exit 1
+        run: |
+          echo "This step will fail but workflow continues"
+          exit 1
 
       - name: This still runs because of continue-on-error
         run: echo "Workflow did not stop"
